### ISSUE TITLE
customized i18n file not overwriting

### ISSUE THREAD

**Issue by Phraqtal** [CodingMinds/CSN#10]
"Previous defined keys (like title, descriptions, etc.) can be overwritten if you place your own i18n file beside the default one and give it a name that ensures that it will be loaded after the default one."

Can you confirm that this is working? I have been unable to get it to work. 

I have tried with the customized file being named as in your example, but have been unable to get it to work. The locales.coll.json file is not overwritten.

**Comment by CodingMinds** [comment]
Have you reload the application after the addition and/or changes ? morbo doesn't observe the i18n directory by default.
Which OS and filesystem do you use ?

I've tested it with a 3.2.0 Linux and a ext3 filesystem. Everything works as expected.

```
ls -1 i18n/
locales.coll.json
xxx.my_locales.coll.json
```

```
cat i18n/xxx.my_locales.coll.json 
{
  "navbar_brand": {
    "en": "Closed social network XXXXXXXXXX",
    "de": "Closed social network XXXXXXXXXX"
  }
}
```

The string "Closed social network XXXXXXXXXX" will be displayed as brand name in the menu bar.

**Comment by Phraqtal** [comment]
Thanks. I'm using Heroku. I upgraded my Heroku stack from Cedar (Ubuntu 10.04) to Cedar-14 (Ubuntu 14.04) and it now works.

**Comment by CodingMinds** [comment]
K. Thanks for your feedback
