### ISSUE TITLE
is_admin column not added to initdb.sql

### ISSUE THREAD

**Issue by Phraqtal** [CodingMinds/CSN#5]
When the is_admin column was added to the Account.pm schema file in the 'add first simple admin dashboard' commit, the column was not added to the initdb.sql file. Was this intentional or an oversight?

It causes an error, 'column is_admin not found' when trying to log in to the app. I added the column definition to the Account table in the db and that resolved the error.

**Comment by CodingMinds** [comment]
Oh this was an oversight. I'll fix it with the next commit, thanks for your feedback.
